terminate called after throwing an instance of 'std::runtime_error'
  what():  
Aborted (core dumped)
